name: ci

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - name: yarn deduplicate
        run: |
          DUPE_LIST=$(yarn run -s yarn-deduplicate --list)
          DUPES=$(printf "$DUPE_LIST" | wc -l | tr -d ' ')
          if [ "$DUPES" -eq 0 ]; then
            echo "no duplicate resolutions to resolve"
            exit 0
          fi
          printf  "duplicates found: \n\n%s" "$DUPE_LIST"
          exit 1
      - run: yarn check-types
      - run: yarn lint:ci
      - run: yarn security
      - run: yarn compile
      - run: yarn test
      - run: yarn deploy:hardhat
